Feature/back button
pirilinchu/Orion pull request #1
Opened 2024-04-10 22:47 UTC by mathpro28

2024-04-10 22:58 UTC, pirilinchu requested changes

2024-04-10 22:58 UTC, pirilinchu commented on Orion/AppInfo.swift
> +    func onBackPressed() {
Deberiamos resetear los valores a los iniciales cuando hacemos back? Por ejemplo el array de people deberia quedar en [] si volvemos a elegir otro mes?

Tambien hay que ver el caso si vuelvo a año, lo cambio, que pasa con el mes que estaba seleccionado?

2024-04-10 22:58 UTC, pirilinchu commented on Orion/OrionView.swift
>  import SwiftUI
Por que mataste el header del file?

2024-04-10 22:58 UTC, pirilinchu commented on Orion/OrionView.swift
> +    var backButton: some View {
Rename it to BackButton

2024-04-10 22:58 UTC, pirilinchu commented on Orion/OrionView.swift
> +            .overlay(backButton, alignment: .topLeading)
Para que un NavigationView vacio? El overlay es suficiente

2024-04-10 22:58 UTC, pirilinchu commented on Orion/OrionView.swift
> +            return AnyView(EmptyView())
Para que no tengas que usar ~~return AnyView~~ agregale @ViewBuilder a esta var
```
@ViewBuilder
var BackButton: some View { 

}
```

2024-04-11 00:00 UTC, mathpro28 commented on Orion/OrionView.swift
>  import SwiftUI
se me fue, lo siento boss

2024-04-11 00:01 UTC, mathpro28 commented on Orion/AppInfo.swift
> +    func onBackPressed() {
lo estoy analizando, gracias

2024-04-11 00:03 UTC, mathpro28 commented on Orion/AppInfo.swift
> +    func onBackPressed() {
quizás no es necesario resetar los valores ya que puede ser que seleccionó un mes por error y al volver quiere conservar los nombres, en todo caso, podríamos resetear al cambiar el año, que opinas?

2024-04-11 00:03 UTC, mathpro28 commented on Orion/OrionView.swift
> +    var backButton: some View {
done

2024-04-11 00:07 UTC, pirilinchu commented on Orion/AppInfo.swift
> +    func onBackPressed() {
Go

2024-04-11 01:19 UTC, merged

2024-04-11 01:20 UTC, pirilinchu commented on Orion/OrionView.swift
> +        } else {
I think you dont need the else

2024-04-11 01:20 UTC, pirilinchu commented on Orion/OrionView.swift
> +        NavigationView {
I think you can remove the NavigationView{}